apiVersion: apps/v1
kind: Deployment
 
metadata:
  name: football-deployment
  namespace: default
  labels:
    app: football
    app.kubernetes.io/managed-by: Helm
 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: football
      app.kubernetes.io/managed-by: Helm
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
      labels:
        app: football
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: golang
          image: adi463/football:latest
          ports:
            - containerPort: 3000