apiVersion: v1
kind: Service
 
metadata:
  name: football-service
  namespace: default
  labels:
    app: football
    app.kubernetes.io/managed-by: Helm
  
 
spec:
  type: NodePort
  selector:
    app: football
  ports:
    - protocol: TCP
      port: 80
      name: http-web
      targetPort: 3000