apiVersion: v1
kind: Service
 
metadata:
  name: football-service
  namespace: default
 
spec:
  type: NodePort
  selector:
    app: football
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000