apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    release: prometheus
  name: common-service-monitor
  namespace: prometheus
spec:
  endpoints:
  - port: http-web
    path: /metrics
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - {key: app.kubernetes.io/managed-by, operator: Exists}